<h1 align="center" style="color:green;font-size: 3em;">Homework 2:
Implementing Fine-tuning Techniques</h1>



# Part 1: Introduction

In this homework, you will implement various fine-tuning methods as described in different papers, specifically LoRA and IA3, and answer some conceptual questions about these techniques. Additionally, you will get an introduction to Hugging Face, a platform offering a wide range of models and datasets.

**Instructions:**
- Follow the notebook sections to implement various fine-tuning techniques.
- Complete the code cells marked with `TODO`.
- Ensure your code runs correctly by the end of the notebook.

# Part 2: Import Libraries

In [ ]:
!pip install datasets -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.7/472.7 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 4.8 MB/s eta 0:00:00


In [ ]:

# importing required libraries
import torch
import torch.nn as nn
import collections
import random
import numpy as np
import math
import matplotlib.pyplot as plt
import warnings

from torch.optim import AdamW
from typing import List
from torch.nn import functional as F
from tqdm import tqdm
from datasets import load_dataset, Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    Trainer,
    DataCollatorForLanguageModeling,
    TrainingArguments,
)
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM, T5Tokenizer, T5ForSequenceClassification
from torch.utils.data import DataLoader

warnings.simplefilter("ignore")
print(torch.__version__)

2.5.0+cu121


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
!git --version


git version 2.34.1


In [ ]:
!git config --global credential.helper store

In [ ]:
!git config --global --get credential.helper


store


In [ ]:
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

# Part 6: IA3 Memory Analysis

In this section, you will perform memory analysis on a well-known model from Hugging Face called Gemma. Gemma is a state-of-the-art model used for various natural language processing tasks. However, it is a "gated model," meaning you must create a Hugging Face account and request access through their portal to use it. Read more about how to get access to gated models [here](https://huggingface.co/docs/hub/en/models-gated).

Run the cells below to download gemma.

In [ ]:
!pip install huggingface_hub -q

In [ ]:
## You will need to re-generate the token everytime you restart the notebook
## Select no for "add token as git credential"
!huggingface-cli login


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    A token is already saved on your machine. Run `huggingface-cli whoami` to get more information or `huggingface-cli logout` if you want to log out.
    Setting a new token will erase the existing one.
    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): 
Add token as git credential? (Y/n) Y
Token is valid (permission: write)

In [ ]:
## TODO: Load the gemma model (NEED AUTHENTICATIOIN)
model_name = "google/gemma-2b"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/33.6k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [ ]:
## Check the model architecture
model

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 2048, padding_idx=0)
    (layers): ModuleList(
      (0-17): 18 x GemmaDecoderLayer(
        (self_attn): GemmaSdpaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=256, bias=False)
          (v_proj): Linear(in_features=2048, out_features=256, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (up_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (down_proj): Linear(in_features=16384, out_features=2048, bias=False)
          (act_fn): PytorchGELUTanh()
        )
        (input_layernorm): GemmaRMSNorm((2048,), eps=1e-06)
        (post_attention_layernorm): GemmaRMSNorm((2048,), eps=1e-

## 6.1 Implement IA3 with activations

Next, similar to how we integrated LoRA adapters into our OPT model, we aim to incorporate IA3 into the Gemma model. You can read more about IA3 [here](https://arxiv.org/pdf/2205.05638). IA3 has two distinct implementations: one that modifies activations (as traditional PEFT frameworks do) and another that adjusts weights and biases to align with the CLAM framework discussed in class. Modifying activations means that during the forward pass, the outputs (also known as activations) of certain layers are adjusted using additional parameters. Manipulating weights and biases, on the other hand, means changing the way we get the weights such that it will still satisfy the fine-tuning technique. Below is an implementation focusing on manipulating activations. Review the code carefully to understand the approach.

In [ ]:
## Running this won't really be helpful for the memory analysis in the next section
class IA3Adapter1(nn.Module):
    def __init__(self, existing_layer, in_features, out_features, ia3_lr, is_feedforward=False):
        nn.Module.__init__(self)
        self.existing_layer = existing_layer
        self.is_feedforward = is_feedforward

        # The trainable weights
        self.ia3_lw = (
            nn.Parameter(
                torch.ones((1, out_features), device="cuda")
            )
            if not is_feedforward
            else nn.Parameter(
                torch.ones((1, in_features), device="cuda")
            )
        )
        nn.init.ones_(self.ia3_lw)

        self.ia3_lr = ia3_lr

    def forward(self, x: torch.Tensor):
        if not self.is_feedforward:
            ## We first get the output of the current layer
            result = self.existing_layer(x)
            result = torch.mul(result, self.ia3_lw)
            return result
        else:
            result = torch.mul(x, self.ia3_lw)
            result = self.existing_layer(result)
            return result

In [ ]:
def calculate_memory_for_layer(layer):
    """
    Calculate memory usage for an IA3 layer in GB.
    Includes both parameters (BF16) and gradients (FP32).
    """
    total_bytes = 0

    # Calculate parameter memory (BF16 = 2 bytes)
    param_bytes = sum(p.numel() * 2 for p in layer.parameters())

    # Calculate gradient memory (FP32 = 4 bytes)
    grad_bytes = sum(p.numel() * 4 for p in layer.parameters())

    total_bytes = param_bytes + grad_bytes
    return total_bytes / (1024 ** 3)  # Convert to GB

In [ ]:
def inject_ia3_into_model(model, ia3_lr=1e-4):
    """
    Inject IA3 adapters into the model and return memory stats.
    """
    memory_stats = {
        'kv_memory_per_block': [],
        'down_proj_memory_per_block': []
    }

    # Iterate through each transformer block
    for i, block in enumerate(model.model.layers):
        # Inject IA3 into key projection
        key_proj = block.self_attn.k_proj
        hidden_size = key_proj.weight.shape[0]
        ia3_key = IA3Adapter1(key_proj, hidden_size, hidden_size, ia3_lr)
        block.self_attn.k_proj = ia3_key

        # Inject IA3 into value projection
        value_proj = block.self_attn.v_proj
        ia3_value = IA3Adapter1(value_proj, hidden_size, hidden_size, ia3_lr)
        block.self_attn.v_proj = ia3_value

        # Inject IA3 into down projection of MLP
        down_proj = block.mlp.down_proj
        intermediate_size = down_proj.weight.shape[1]
        ia3_down = IA3Adapter1(down_proj, intermediate_size, hidden_size, ia3_lr, is_feedforward=True)
        block.mlp.down_proj = ia3_down

        # Calculate memory for this block
        kv_memory = calculate_memory_for_layer(ia3_key) + calculate_memory_for_layer(ia3_value)
        down_proj_memory = calculate_memory_for_layer(ia3_down)

        memory_stats['kv_memory_per_block'].append(kv_memory)
        memory_stats['down_proj_memory_per_block'].append(down_proj_memory)

    return model, memory_stats



In [ ]:
def ia3_activation(model):


    # Inject IA3 and get memory stats
    model, memory_stats = inject_ia3_into_model(model)

    # Print results
    print("\nIA3 Memory Requirements Analysis:")
    print("-" * 50)

    for block_idx in range(len(memory_stats['kv_memory_per_block'])):
        print(f"\nTransformer Block {block_idx}:")
        kv_mem = memory_stats['kv_memory_per_block'][block_idx]
        down_mem = memory_stats['down_proj_memory_per_block'][block_idx]
        total_mem = kv_mem + down_mem

        print(f"Key and Value Matrices: {kv_mem:.6f} GB")
        print(f"Down Projection Layer: {down_mem:.6f} GB")
        print(f"Total for block: {total_mem:.6f} GB")

    # Calculate averages
    avg_kv = np.mean(memory_stats['kv_memory_per_block'])
    avg_down = np.mean(memory_stats['down_proj_memory_per_block'])
    avg_total = avg_kv + avg_down

    print("\nAverage Memory Per Block:")
    print("-" * 50)
    print(f"Average Key and Value Matrices: {avg_kv:.6f} GB")
    print(f"Average Down Projection Layer: {avg_down:.6f} GB")
    print(f"Average Total per block: {avg_total:.6f} GB")

    return

In [ ]:
ia3_activation(model)

In [ ]:
model

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 2048, padding_idx=0)
    (layers): ModuleList(
      (0-17): 18 x GemmaDecoderLayer(
        (self_attn): GemmaSdpaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): IA3Adapter1(
            (existing_layer): Linear(in_features=2048, out_features=256, bias=False)
          )
          (v_proj): IA3Adapter1(
            (existing_layer): Linear(in_features=2048, out_features=256, bias=False)
          )
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (up_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (down_proj): IA3Adapter1(
            (existing_layer): Linear(in_features=16384, out_features=2048, bias=False)
          )
        

## 6.2 Memory analysis

<h3>Task:</h3>

With the activations method, calculate (and show your work) the memory requirement (return result in GB) of each forward pass when we try to inject IA3 into the **key and value matrices** of **each transformer block** in gemma and the **down_proj** layer of the mlp layer.

```
Hint 1: First calculate how many GB of memory per block (separate KV calculations from down_proj calculations)
```

```
Hint 2: The parameter weights of gemma is stored in Brain Float 16 which is 2 bytes (or 16 bits)
```

```
Hint 3: Gradients are stored in 4 bytes (or 32 bits)
```

```
Hint 4: Disregard the calculations related to the optimizer
```

```
Hint 5: Also need to take care of the calculations for the additional trainable parameters
```

In [ ]:
def calculate_memory_requirements():
    # Model dimensions from the architecture
    input_dim = 2048
    kv_dim = 256
    down_proj_input = 16384
    down_proj_output = 2048

    def calculate_kv_memory():
        """Calculate memory for K and V operations"""
        # Original parameters (BF16 = 2 bytes) - frozen, no gradients needed
        orig_params = 2 * (input_dim * kv_dim * 2)  # 2 for K and V matrices

        # IA3 parameters (BF16 = 2 bytes)
        ia3_params = 2 * (1 * kv_dim * 2)  # 2 for K and V adapters

        # IA3 gradients (FP32 = 4 bytes) - only for trainable IA3 parameters
        ia3_grads = 2 * (1 * kv_dim * 4)  # 2 for K and V adapters
        print(orig_params , ia3_params , ia3_grads)

        total_bytes = orig_params + ia3_params + ia3_grads
        return total_bytes / (1024 ** 3)  # Convert to GB

    def calculate_down_proj_memory():
        """Calculate memory for down_proj operations"""
        # Original parameters (BF16 = 2 bytes) - frozen, no gradients needed
        orig_params = down_proj_input * down_proj_output * 2

        # IA3 parameters (BF16 = 2 bytes)
        ia3_params = 1 * down_proj_input * 2

        # IA3 gradients (FP32 = 4 bytes) - only for trainable IA3 parameters
        ia3_grads = 1 * down_proj_input * 4

        total_bytes = orig_params + ia3_params + ia3_grads
        print(orig_params ,ia3_params ,ia3_grads)
        return total_bytes / (1024 ** 3)  # Convert to GB

    # Calculate totals
    kv_memory = calculate_kv_memory()
    down_proj_memory = calculate_down_proj_memory()
    total_memory = kv_memory + down_proj_memory

    # Print detailed breakdown
    print("\nMemory Requirements per Forward Pass (GB):")
    print("-" * 50)
    print(f"\nKey and Value Matrices:")
    print(f"Memory: {kv_memory:.6f} GB")
    print("Includes:")
    print("- Original K/V parameters (BF16) - frozen")
    print("- IA3 K/V parameters (BF16)")
    print("- IA3 K/V gradients (FP32)")

    print(f"\nDown Projection Layer:")
    print(f"Memory: {down_proj_memory:.6f} GB")
    print("Includes:")
    print("- Original down_proj parameters (BF16) - frozen")
    print("- IA3 down_proj parameters (BF16)")
    print("- IA3 down_proj gradients (FP32)")

    print(f"\nTotal Memory per Block: {total_memory:.6f} GB")

    return {
        'kv_memory': kv_memory,
        'down_proj_memory': down_proj_memory,
        'total_memory': total_memory
    }


memory_reqs = calculate_memory_requirements()

2097152 1024 2048
67108864 32768 65536

Memory Requirements per Forward Pass (GB):
--------------------------------------------------

Key and Value Matrices:
Memory: 0.001956 GB
Includes:
- Original K/V parameters (BF16) - frozen
- IA3 K/V parameters (BF16)
- IA3 K/V gradients (FP32)

Down Projection Layer:
Memory: 0.062592 GB
Includes:
- Original down_proj parameters (BF16) - frozen
- IA3 down_proj parameters (BF16)
- IA3 down_proj gradients (FP32)

Total Memory per Block: 0.064548 GB



Normal IA3 (IA3 Adapter 1)

For K,V:
x (batched): [32,216,2048] (batch size, sequence length, hidden dim) (not counted towards memory)

self.existing_layer(x)’s shape:      [32,216, 256] (using the code to find shapes may help fill in the blanks)

torch.mul(result, self.ia3_lw) result’s shape:      [32,  216,  256]

Total = 2 matrices KV * 2 computations * 32 (first value of the shape of the previous operation)* 216 (second value of the shape of the previous operation) * 256 (third value of the shape of the previous operation * 16 bits per number) / 8 bits per byte = 14155776 bytes


For down_proj:
x (batched): [32,216,16384] (not counted towards memory)

torch.mul(x, self.ia3_lw): [32, 216, 16384]

self.existing_layer(result): [32, 216, 2048]

Total = (32 * 216 * 16384 + 32 * 16 * 2048)  * 16 bits per number / 8 bits per byte =  254803968  bytes 



Total activations size per block = 14155776 bytes + 254803968 bytes = 0.25048828125  GB


Total IA3 activation size for model  = 0.25048828125 GB * 18 blocks = 4.5087890625 GB

We also introduce more trainable parameters, whose weight values, gradients, and gradient moments need to be tracked for the optimizer.  Assume we are using the Adam optimizer, which requires 2 gradient moments to be stored per trainable parameter.

Total trainable parameters: 16384+256+256= 16896

Param weights (bf16): 16896 params * 2 bytes = 33792 bytes

Gradients (32 bit) = 16896 params * 4 bytes = 67584 bytes

Gradient moments (32 bit) = 16896 params * 2 moments * 4 bytes = 135168 bytes

Total additional memory for params:18*（33792+67584+135168）bytes =  0.0039653778 GB


## 6.3 Implement IA3 in CLAM

Below is another class similar to the one in section 4.1. However, this implementation modifies the weights and biases directly instead of manipulating activations. Review the code carefully to understand this alternative approach.


In [ ]:
## Part of the CLAM abstraction (should not compile)
class IA3Adapter2(nn.Module):
    def __init__(self, existing_layer, in_features, out_features, ia3_lr, is_feedforward=False):
        nn.Module.__init__(self)
        self.existing_layer = existing_layer
        self.is_feedforward = is_feedforward
        self.ia3_lw = (
            nn.Parameter(
                torch.ones((1, out_features), device="cuda")
            )
            if not is_feedforward
            else nn.Parameter(
                torch.ones((1, in_features), device="cuda")
            )
        )
        nn.init.ones_(self.ia3_lw)

        self.ia3_lr = ia3_lr


    ## Everytime we run the forward method, we will get the corresponding weights and biases
    def forward(self, x: torch.Tensor):
        return F.linear(
            self.get_equivalent_weight(),
            self.get_equivalent_bias(),
            x
        )

    def get_equivalent_weight(self):
        """
        Converts IA3 layer to equivalent nn.Linear weight tensor
        """
        mat = self.get_weight()
        ret_weight = None
        if not self.is_feedforward:
            ret_weight = torch.diag(self.ia3_lw.view(-1)) @ mat
        else:
            ret_weight = mat @ torch.diag(self.ia3_lw.view(-1))

        return ret_weight


    def get_equivalent_bias(self):
        """
        Gets equivalent nn.Linear bias data
        """
        mat = self.get_bias()
        if mat is None:
            return None
        ret_bias = None

        if not self.is_feedforward:
            ret_bias = torch.mul(mat, self.ia3_lw.squeeze())
        else:
            ret_bias = mat

        return ret_bias

## 6.4 Memory analysis

<h3>Task:</h3>

Under similar settings as 6.2. Perform memory analysis again.



IA3 Adapter 2
For K,V Operations:
Initial shape: [32, 216, 2048]

For non-feedforward case:

1.	get_equivalent_weight(): 

Creates diagonal matrix from ia3_lw: [256, 256]

Matrix multiplication with original weights: [256, 256] @ [256, 2048]

Result shape: [256, 2048]

2.	get_equivalent_bias(): 

Element-wise multiplication of bias with ia3_lw

Result shape: [256]

3.	Final linear operation: 

Input: [32, 216, 2048]

Output: [32, 216, 256]

Total memory = 2 matrices KV * ( # Output activation  32 * 216 * 256 + # Diagonal matrix  256 * 256 + # Equivalent weight matrix 256 * 2048 ) * 16 bits / 8 bytes = 9437184 bytes

For down_proj:

Input shape: [32, 216, 16384]

For feedforward case:

1.	get_equivalent_weight(): 
Creates diagonal matrix from ia3_lw: [16384, 16384]
Matrix multiplication with original weights: [2048, 16384] @ [16384, 16384]
Result shape: [2048, 16384]
2.	Final linear operation: 
Input: [32, 216, 16384]
Output: [32, 216, 2048]
Total memory = ( # Output activations  32 * 216 * 2048 + # Diagonal matrix 16384 * 16384 + # Equivalent weight matrix  2048 * 16384 ) * 16 bits / 8 bytes = 632291328 bytes


Total Memory Per Block
9437184 + 632291328 = 641728512 bytes ≈ 0.59765625 GB


Total Model Memory (18 blocks)
0.59765625 * 18 = 10.7578125 GB


Additional Parameters Memory


Same as IA3Adapter1 since parameter count is identical:
•	Total params: 16,896
•	Parameter weights (bf16): 33,792 bytes
•	Gradients (32-bit): 67,584 bytes
•	Gradient moments (32-bit): 135,168 bytes

Total additional memory for params:18*（33792+67584+135168）bytes =  0.0039653778 GB


## 6.5 Conceptual Questions

**Question:** Is there a difference between what you calculated in 6.2 and what you calculated in 6.4? Why does this make sense?

  **Your Answer:**

  The memory calculated in 6.4 is much higher than it in 6.2. The reason is that we map the IA3 adapter to the dimension of orignal K, V and the down_proj_layer, so we need additional memories to store the mapped diagonal matrix.